

import {
  Wifi,
  Car,
  Tv,
  Utensils,
  Waves,
  Snowflake,
  BedDouble,
  Bath,
  WashingMachine,
  Refrigerator,
  Coffee,
  Flame,
  Wind,
  Sun,
  Mountain,
  TreePalm,
  Home,
  Building,
  MapPin,
  ParkingCircle,
  Sofa,
  Lamp,
  Star,
  Dumbbell,
  ShieldCheck,
  Camera,
  Lock,
  KeyRound,
  Bike,
  Plane,
  Globe,
  Crown,
  Sparkles,
  Diamond,
  ShowerHead,
  Droplets,
  Heater,
  SoapDispenserDroplet,
  Thermometer,
  Toilet,
  Clock,
  Archive,
  Moon,
  Plug,
  Microwave,
  Baby,
  Cigarette,
  PartyPopper,
  Dog,
} from "lucide-react";

export const amenityIcons = [
  { name: "wifi", icon: Wifi },
  { name: "parking", icon: Car },
  { name: "tv", icon: Tv },
  { name: "kitchen", icon: Utensils },
  { name: "pool", icon: Waves },
  { name: "ac", icon: Snowflake },

  { name: "bedroom", icon: BedDouble },
  { name: "bathroom", icon: Bath },
  { name: "washing_machine", icon: WashingMachine },
  { name: "refrigerator", icon: Refrigerator },
  { name: "coffee_machine", icon: Coffee },

  { name: "bbq", icon: Flame },
  { name: "balcony", icon: Wind },
  { name: "terrace", icon: Sun },

  { name: "mountain_view", icon: Mountain },
  { name: "garden", icon: TreePalm },

  { name: "entire_home", icon: Home },
  { name: "apartment", icon: Building },
  { name: "location", icon: MapPin },

  { name: "private_parking", icon: ParkingCircle },

  { name: "living_room", icon: Sofa },
  { name: "bedside_lamp", icon: Lamp },

  { name: "top_rated", icon: Star },
  { name: "gym", icon: Dumbbell },

  { name: "security", icon: ShieldCheck },
  { name: "cctv", icon: Camera },
  { name: "smart_lock", icon: Lock },
  { name: "self_checkin", icon: KeyRound },

  { name: "bicycle", icon: Bike },
  { name: "airport_nearby", icon: Plane },
  { name: "tourist_friendly", icon: Globe },

  { name: "luxury", icon: Crown },
  { name: "premium", icon: Sparkles },
  { name: "exclusive", icon: Diamond },

  { name: "shower", icon: ShowerHead },
  { name: "hot_water", icon: Thermometer },
  { name: "toiletries", icon: SoapDispenserDroplet },
  { name: "towels", icon: Droplets },

  { name: "water_heater", icon: Heater },
  { name: "toilet", icon: Toilet },

  { name: "alarm_clock", icon: Clock },
  { name: "wardrobe", icon: Archive },
  { name: "night_light", icon: Moon },
  { name: "charging_point", icon: Plug },

  { name: "microwave", icon: Microwave },

  { name: "children_allowed", icon: Baby },
  { name: "smoking_allowed", icon: Cigarette },
  { name: "events_allowed", icon: PartyPopper },
  { name: "pets_allowed", icon: Dog },
];
